const questions = [
  // ─── MATHEMATICS (20 questions) ───────────────────────────

  {
    questionText: "What is the value of x if 2x + 6 = 14?",
    options: ["3", "4", "6", "8"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Linear Equations",
    explanation: "2x = 14 - 6 = 8, therefore x = 4",
    year: 2020,
  },
  {
    questionText:
      "What is the slope of the line passing through points (2, 3) and (4, 7)?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Coordinate Geometry",
    explanation:
      "slope = (y2 - y1) / (x2 - x1) = (7 - 3) / (4 - 2) = 4 / 2 = 2",
    year: 2019,
  },
  {
    questionText: "If f(x) = x² + 3x - 4, what is f(2)?",
    options: ["4", "6", "8", "10"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Functions",
    explanation: "f(2) = (2)² + 3(2) - 4 = 4 + 6 - 4 = 6",
    year: 2021,
  },
  {
    questionText: "What is the value of log₂(64)?",
    options: ["4", "5", "6", "8"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Logarithms",
    explanation: "log₂(64) = log₂(2⁶) = 6",
    year: 2020,
  },
  {
    questionText: "The sum of the interior angles of a hexagon is:",
    options: ["540°", "620°", "720°", "800°"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Geometry",
    explanation:
      "Sum of interior angles = (n - 2) × 180° = (6 - 2) × 180° = 720°",
    year: 2018,
  },
  {
    questionText: "What is the solution set of |x - 3| = 5?",
    options: [
      "x = 2 or x = 8",
      "x = -2 or x = 8",
      "x = -8 or x = 2",
      "x = -8 or x = -2",
    ],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Absolute Value",
    explanation:
      "|x - 3| = 5 means x - 3 = 5 giving x = 8, or x - 3 = -5 giving x = -2",
    year: 2019,
  },
  {
    questionText: "If the determinant of matrix A = [[3, 2], [1, 4]] is:",
    options: ["8", "10", "12", "14"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Matrices",
    explanation: "det(A) = (3 × 4) - (2 × 1) = 12 - 2 = 10",
    year: 2021,
  },
  {
    questionText:
      "What is the 10th term of the arithmetic sequence 3, 7, 11, 15, ...?",
    options: ["35", "39", "43", "47"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Sequences and Series",
    explanation: "aₙ = a₁ + (n-1)d = 3 + (10-1)×4 = 3 + 36 = 39",
    year: 2018,
  },
  {
    questionText: "What is the value of sin(60°)?",
    options: ["1/2", "√2/2", "√3/2", "√3/3"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Trigonometry",
    explanation: "sin(60°) = √3/2 ≈ 0.866",
    year: 2020,
  },
  {
    questionText:
      "What is the area of a circle with radius 7 cm? (Use π = 22/7)",
    options: ["44 cm²", "88 cm²", "154 cm²", "308 cm²"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Mensuration",
    explanation: "Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm²",
    year: 2019,
  },
  {
    questionText: "Which of the following is a factor of x² - 5x + 6?",
    options: ["(x - 1)", "(x - 2)", "(x + 2)", "(x + 3)"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Factorization",
    explanation: "x² - 5x + 6 = (x - 2)(x - 3), so (x - 2) is a factor",
    year: 2021,
  },
  {
    questionText: "If 3x - 2y = 12 and x + y = 1, what is the value of x?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Simultaneous Equations",
    explanation:
      "From x + y = 1, y = 1 - x. Substituting: 3x - 2(1-x) = 12, 5x = 14... solving gives x = 2 when y = -1 check: 3(2)-2(-1)=8≠12. Correct: x=2, y=-1. 3(2)-2(-1)=6+2=8. Actually x=14/5. Recheck: 3x-2(1-x)=12 → 5x-2=12 → x=14/5",
    year: 2020,
  },
  {
    questionText: "What is the value of ⁵C₂?",
    options: ["5", "10", "15", "20"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Combinations",
    explanation: "⁵C₂ = 5! / (2! × 3!) = (5 × 4) / (2 × 1) = 10",
    year: 2019,
  },
  {
    questionText:
      "What is the range of the function f(x) = x² + 1 for all real x?",
    options: ["y ≥ 0", "y ≥ 1", "y > 1", "all real numbers"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Functions",
    explanation:
      "Since x² ≥ 0 for all real x, x² + 1 ≥ 1. The minimum value is 1 when x = 0.",
    year: 2021,
  },
  {
    questionText:
      "What is the probability of getting a head when a fair coin is tossed once?",
    options: ["1/4", "1/3", "1/2", "3/4"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Probability",
    explanation:
      "A fair coin has 2 equally likely outcomes (head or tail). P(head) = 1/2",
    year: 2018,
  },
  {
    questionText: "If a = 2 and b = -3, what is the value of a² - 2ab + b²?",
    options: ["1", "5", "25", "49"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Algebra",
    explanation: "a² - 2ab + b² = (a - b)² = (2 - (-3))² = 5² = 25",
    year: 2020,
  },
  {
    questionText:
      "What is the perimeter of an equilateral triangle with side length 8 cm?",
    options: ["16 cm", "20 cm", "24 cm", "32 cm"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Geometry",
    explanation: "Perimeter of equilateral triangle = 3 × side = 3 × 8 = 24 cm",
    year: 2019,
  },
  {
    questionText: "Evaluate: lim(x→2) (x² - 4) / (x - 2)",
    options: ["0", "2", "4", "undefined"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Calculus - Limits",
    explanation: "(x² - 4)/(x - 2) = (x+2)(x-2)/(x-2) = x+2. As x→2, limit = 4",
    year: 2021,
  },
  {
    questionText: "What is the geometric mean of 4 and 16?",
    options: ["6", "8", "10", "12"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Sequences and Series",
    explanation: "Geometric mean = √(4 × 16) = √64 = 8",
    year: 2018,
  },
  {
    questionText:
      "If the roots of the equation x² - 5x + k = 0 are equal, what is k?",
    options: ["4", "5", "6.25", "25"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Quadratic Equations",
    explanation:
      "For equal roots, discriminant = 0. b² - 4ac = 0. 25 - 4k = 0. k = 25/4 = 6.25",
    year: 2020,
  },

  // ─── ENGLISH (20 questions) ───────────────────────────────

  {
    questionText: "Choose the word that is closest in meaning to DILIGENT:",
    options: ["Lazy", "Hardworking", "Clever", "Honest"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Vocabulary - Synonyms",
    explanation:
      "Diligent means showing care and effort in work, which is the same as hardworking.",
    year: 2019,
  },
  {
    questionText: "Which sentence is grammatically correct?",
    options: [
      "She don't know the answer.",
      "They was going to school.",
      "He has been studying for three hours.",
      "We is happy today.",
    ],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Present Perfect Continuous",
    explanation:
      "Option C uses the present perfect continuous tense correctly: Subject + has/have + been + verb-ing.",
    year: 2020,
  },
  {
    questionText: "Choose the antonym of ANCIENT:",
    options: ["Old", "Historical", "Modern", "Primitive"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Vocabulary - Antonyms",
    explanation:
      "Ancient means very old. Its antonym (opposite) is modern, meaning new or current.",
    year: 2018,
  },
  {
    questionText:
      'Identify the type of sentence: "What a beautiful day it is!"',
    options: ["Declarative", "Interrogative", "Imperative", "Exclamatory"],
    correctAnswer: 3,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Types of Sentences",
    explanation:
      "A sentence that expresses strong emotion and ends with an exclamation mark is exclamatory.",
    year: 2021,
  },
  {
    questionText:
      'Choose the correct passive voice: "The teacher teaches the students."',
    options: [
      "The students are taught by the teacher.",
      "The students were taught by the teacher.",
      "The students have been taught by the teacher.",
      "The students taught by the teacher.",
    ],
    correctAnswer: 0,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Passive Voice",
    explanation:
      'Present simple active → present simple passive: am/is/are + past participle. "teaches" becomes "are taught by".',
    year: 2019,
  },
  {
    questionText:
      'Which word correctly completes the sentence: "She is _____ honest person."',
    options: ["a", "an", "the", "no article needed"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Articles",
    explanation:
      'We use "an" before words that begin with a vowel sound. "Honest" starts with a silent H so it has a vowel sound /ɒ/.',
    year: 2020,
  },
  {
    questionText: 'The word "BENEVOLENT" most nearly means:',
    options: ["Cruel", "Kind and generous", "Intelligent", "Brave"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Vocabulary",
    explanation:
      "Benevolent means well-meaning and kindly, characterized by doing good.",
    year: 2021,
  },
  {
    questionText:
      'Choose the correct form of the verb: "Neither the students nor the teacher _____ present."',
    options: ["are", "were", "is", "have been"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Grammar - Subject-Verb Agreement",
    explanation:
      'With "neither...nor", the verb agrees with the subject closest to it. "teacher" is singular, so use "is".',
    year: 2019,
  },
  {
    questionText:
      'Which literary device is used in "The wind whispered through the trees"?',
    options: ["Simile", "Metaphor", "Personification", "Alliteration"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Literary Devices",
    explanation:
      "Personification gives human qualities (whispering) to non-human things (wind).",
    year: 2020,
  },
  {
    questionText:
      'Choose the word that best completes the sentence: "The scientist made a remarkable _____ that changed medicine forever."',
    options: ["discover", "discovery", "discovered", "discoverer"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Vocabulary - Word Forms",
    explanation:
      'We need a noun after "remarkable". "Discovery" is the correct noun form of the verb "discover".',
    year: 2018,
  },
  {
    questionText:
      'What is the correct indirect speech for: He said, "I am going to school."',
    options: [
      "He said that he is going to school.",
      "He said that he was going to school.",
      "He said that I was going to school.",
      "He said that he goes to school.",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Reported Speech",
    explanation:
      'In reported speech, present continuous "am going" becomes past continuous "was going". Pronoun "I" changes to "he".',
    year: 2021,
  },
  {
    questionText: "Which sentence contains a dangling modifier?",
    options: [
      "Running fast, John won the race.",
      "Running fast, the race was won.",
      "John, running fast, won the race.",
      "The race was won by John who was running fast.",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Grammar - Modifiers",
    explanation:
      'Option B has a dangling modifier. "Running fast" should modify a person, but the sentence says "the race" was running fast.',
    year: 2020,
  },
  {
    questionText:
      'Choose the correct preposition: "She has been waiting _____ two hours."',
    options: ["since", "for", "from", "during"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Prepositions",
    explanation:
      'We use "for" with a period of time (two hours). "Since" is used with a specific point in time.',
    year: 2019,
  },
  {
    questionText: 'The phrase "a blessing in disguise" means:',
    options: [
      "Something that appears bad but turns out to be good",
      "A gift given secretly",
      "A lucky escape from danger",
      "Something valuable hidden underground",
    ],
    correctAnswer: 0,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Idioms and Phrases",
    explanation:
      '"A blessing in disguise" is an idiom meaning something that seems bad or unlucky at first but results in something good.',
    year: 2021,
  },
  {
    questionText: 'Identify the figure of speech: "Life is a journey."',
    options: ["Simile", "Metaphor", "Hyperbole", "Personification"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Literary Devices",
    explanation:
      'A metaphor makes a direct comparison without using "like" or "as". "Life IS a journey" is a metaphor.',
    year: 2018,
  },
  {
    questionText: "Choose the correct spelling:",
    options: ["Accomodation", "Accommodation", "Acomodation", "Acommodation"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Spelling",
    explanation:
      'The correct spelling is "Accommodation" with double c and double m.',
    year: 2020,
  },
  {
    questionText:
      'Which word is a conjunction in the sentence: "I was tired, but I continued working."',
    options: ["tired", "continued", "but", "working"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Parts of Speech",
    explanation:
      '"But" is a coordinating conjunction that connects two independent clauses.',
    year: 2019,
  },
  {
    questionText:
      'What does the prefix "mis-" mean in the word "misunderstand"?',
    options: ["before", "again", "wrongly", "not"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Word Formation - Prefixes",
    explanation:
      'The prefix "mis-" means wrongly or incorrectly. "Misunderstand" means to understand wrongly.',
    year: 2021,
  },
  {
    questionText: "Choose the sentence with the correct use of the apostrophe:",
    options: [
      "The dog wagged it's tail.",
      "The dogs' food was eaten.",
      "Its a beautiful morning.",
      "The childrens' toys were scattered.",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Grammar - Apostrophes",
    explanation:
      '"The dogs\' food" correctly shows plural possessive. "it\'s" means "it is", "its" is possessive.',
    year: 2020,
  },
  {
    questionText: 'The word "LOQUACIOUS" means:',
    options: [
      "Silent and reserved",
      "Talkative",
      "Intelligent and wise",
      "Angry and violent",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Vocabulary",
    explanation: "Loquacious means tending to talk a great deal; talkative.",
    year: 2018,
  },

  // ─── BIOLOGY (20 questions) ───────────────────────────────

  {
    questionText: "Which organelle is known as the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Apparatus"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Cell Biology",
    explanation:
      'Mitochondria produce ATP energy through cellular respiration, earning the name "powerhouse of the cell".',
    year: 2019,
  },
  {
    questionText:
      "What type of blood cells are responsible for carrying oxygen throughout the body?",
    options: ["White blood cells", "Platelets", "Red blood cells", "Plasma"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Blood and Circulatory System",
    explanation:
      "Red blood cells (erythrocytes) contain hemoglobin which binds to and carries oxygen from the lungs to body tissues.",
    year: 2020,
  },
  {
    questionText:
      "Which process converts glucose into ATP in the absence of oxygen?",
    options: [
      "Aerobic respiration",
      "Photosynthesis",
      "Anaerobic respiration",
      "Transpiration",
    ],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Cellular Respiration",
    explanation:
      "Anaerobic respiration (fermentation) produces ATP from glucose without oxygen, yielding lactic acid or ethanol.",
    year: 2021,
  },
  {
    questionText: "What is the basic unit of heredity?",
    options: ["Cell", "Chromosome", "Gene", "DNA"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Genetics",
    explanation:
      "A gene is the basic unit of heredity. It is a specific sequence of DNA that codes for a protein or characteristic.",
    year: 2018,
  },
  {
    questionText:
      "During which phase of mitosis do chromosomes align at the cell's equatorial plate?",
    options: ["Prophase", "Metaphase", "Anaphase", "Telophase"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Cell Division",
    explanation:
      "During metaphase, chromosomes line up along the metaphase plate (equatorial plate) of the cell.",
    year: 2020,
  },
  {
    questionText:
      "Which hormone is responsible for regulating blood glucose levels?",
    options: ["Adrenaline", "Insulin", "Estrogen", "Thyroxine"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Endocrine System",
    explanation:
      "Insulin is produced by the pancreas and lowers blood glucose levels by promoting glucose uptake into cells.",
    year: 2019,
  },
  {
    questionText:
      "What is the process by which plants make their own food using sunlight?",
    options: ["Respiration", "Transpiration", "Photosynthesis", "Fermentation"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Photosynthesis",
    explanation:
      "Photosynthesis is the process where plants use sunlight, water, and CO₂ to produce glucose and oxygen.",
    year: 2021,
  },
  {
    questionText: "Which part of the brain controls balance and coordination?",
    options: ["Cerebrum", "Cerebellum", "Medulla oblongata", "Hypothalamus"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Nervous System",
    explanation:
      "The cerebellum coordinates voluntary movements, balance, and fine motor skills.",
    year: 2018,
  },
  {
    questionText:
      "What is the correct sequence of blood flow through the heart?",
    options: [
      "Right atrium → Left atrium → Left ventricle → Right ventricle",
      "Right atrium → Right ventricle → Lungs → Left atrium → Left ventricle",
      "Left atrium → Right atrium → Right ventricle → Left ventricle",
      "Left ventricle → Left atrium → Right atrium → Right ventricle",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Circulatory System",
    explanation:
      "Deoxygenated blood flows: Right atrium → Right ventricle → Lungs (to get oxygenated) → Left atrium → Left ventricle → Body.",
    year: 2020,
  },
  {
    questionText:
      "Which vitamin is produced by the human body when exposed to sunlight?",
    options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
    correctAnswer: 3,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Nutrition and Health",
    explanation:
      "Vitamin D is synthesized in the skin when exposed to ultraviolet (UV) radiation from sunlight.",
    year: 2019,
  },
  {
    questionText: "What is the function of the nephron in the kidney?",
    options: [
      "Produce blood cells",
      "Filter blood and produce urine",
      "Produce hormones",
      "Store urine",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Excretory System",
    explanation:
      "The nephron is the functional unit of the kidney that filters blood, reabsorbs useful substances, and produces urine.",
    year: 2021,
  },
  {
    questionText:
      "Which type of RNA carries amino acids to the ribosome during protein synthesis?",
    options: ["mRNA", "rRNA", "tRNA", "snRNA"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Molecular Biology",
    explanation:
      "tRNA (transfer RNA) carries specific amino acids to the ribosome and matches them to the mRNA codons during translation.",
    year: 2020,
  },
  {
    questionText: "What is osmosis?",
    options: [
      "Movement of solute from high to low concentration",
      "Movement of water from high to low solute concentration",
      "Active transport of minerals",
      "Movement of water from low to high water concentration",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Transport in Cells",
    explanation:
      "Osmosis is the movement of water molecules through a semi-permeable membrane from a region of low solute concentration to high solute concentration.",
    year: 2018,
  },
  {
    questionText: "Which kingdom do mushrooms belong to?",
    options: ["Plantae", "Animalia", "Fungi", "Protista"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Classification of Living Things",
    explanation:
      "Mushrooms belong to the Kingdom Fungi. They are neither plants nor animals and get nutrients by decomposing organic matter.",
    year: 2019,
  },
  {
    questionText: "What is the role of white blood cells in the body?",
    options: [
      "Carry oxygen",
      "Clot blood",
      "Fight infections",
      "Transport nutrients",
    ],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Immune System",
    explanation:
      "White blood cells (leukocytes) are part of the immune system and defend the body against infections and diseases.",
    year: 2021,
  },
  {
    questionText: "Which gas is released during photosynthesis?",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Photosynthesis",
    explanation:
      "During photosynthesis, plants split water molecules and release oxygen as a byproduct: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂",
    year: 2020,
  },
  {
    questionText:
      "What is the term for the physical appearance of an organism resulting from its genetic makeup?",
    options: ["Genotype", "Phenotype", "Allele", "Chromosome"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Genetics",
    explanation:
      "Phenotype refers to the observable characteristics of an organism, while genotype refers to its genetic makeup.",
    year: 2018,
  },
  {
    questionText: "In which organelle does protein synthesis take place?",
    options: ["Mitochondria", "Nucleus", "Ribosome", "Chloroplast"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Cell Biology",
    explanation:
      "Ribosomes are the sites of protein synthesis (translation), where mRNA is read and amino acids are assembled into proteins.",
    year: 2019,
  },
  {
    questionText: "What is the Hardy-Weinberg principle used for?",
    options: [
      "Predicting mutation rates",
      "Describing allele frequencies in a population",
      "Measuring natural selection",
      "Calculating DNA replication speed",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Population Genetics",
    explanation:
      "The Hardy-Weinberg principle states that allele and genotype frequencies in a population remain constant from generation to generation in the absence of evolutionary influences.",
    year: 2021,
  },
  {
    questionText: "Which structure controls what enters and exits the cell?",
    options: ["Cell wall", "Cell membrane", "Nucleus", "Cytoplasm"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Cell Biology",
    explanation:
      "The cell membrane (plasma membrane) is selectively permeable and regulates the movement of substances in and out of the cell.",
    year: 2020,
  },

  // ─── CHEMISTRY (20 questions) ─────────────────────────────

  {
    questionText: "What is the chemical symbol for Gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Periodic Table",
    explanation: 'Au comes from the Latin word "Aurum" meaning gold.',
    year: 2019,
  },
  {
    questionText: "How many electrons does a Carbon atom have?",
    options: ["4", "6", "8", "12"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Atomic Structure",
    explanation:
      "Carbon has atomic number 6, meaning it has 6 protons. In a neutral atom, the number of electrons equals the number of protons.",
    year: 2020,
  },
  {
    questionText: "What is the pH of a neutral solution at 25°C?",
    options: ["0", "5", "7", "14"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Acids and Bases",
    explanation:
      "A neutral solution has equal concentrations of H⁺ and OH⁻ ions. At 25°C, this corresponds to pH = 7.",
    year: 2018,
  },
  {
    questionText:
      "Which type of bond is formed when electrons are shared between two atoms?",
    options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Chemical Bonding",
    explanation:
      "Covalent bonds are formed when two atoms share one or more pairs of electrons.",
    year: 2021,
  },
  {
    questionText: "What is the molecular formula of water?",
    options: ["HO", "H₂O", "H₂O₂", "HO₂"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Chemical Formulas",
    explanation:
      "Water consists of 2 hydrogen atoms and 1 oxygen atom, giving the molecular formula H₂O.",
    year: 2019,
  },
  {
    questionText: "Which element has the highest electronegativity?",
    options: ["Oxygen", "Chlorine", "Nitrogen", "Fluorine"],
    correctAnswer: 3,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Periodic Trends",
    explanation:
      "Fluorine has the highest electronegativity (3.98 on the Pauling scale) of all elements.",
    year: 2020,
  },
  {
    questionText: "What is the chemical formula for sulfuric acid?",
    options: ["HCl", "HNO₃", "H₂SO₄", "H₃PO₄"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Acids and Bases",
    explanation:
      "Sulfuric acid has the chemical formula H₂SO₄. It is a strong diprotic acid.",
    year: 2021,
  },
  {
    questionText:
      "In the reaction 2H₂ + O₂ → 2H₂O, what is the ratio of hydrogen to oxygen?",
    options: ["1:1", "1:2", "2:1", "2:2"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Stoichiometry",
    explanation:
      "From the balanced equation, 2 moles of H₂ react with 1 mole of O₂. The ratio of H₂ to O₂ is 2:1.",
    year: 2018,
  },
  {
    questionText:
      "Which gas is produced when zinc reacts with dilute hydrochloric acid?",
    options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Reactions of Metals",
    explanation:
      "Zn + 2HCl → ZnCl₂ + H₂. Hydrogen gas is produced when zinc reacts with dilute hydrochloric acid.",
    year: 2019,
  },
  {
    questionText: "What is the oxidation state of sulfur in H₂SO₄?",
    options: ["+2", "+4", "+6", "+8"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Oxidation States",
    explanation: "In H₂SO₄: 2(+1) + S + 4(-2) = 0. So 2 + S - 8 = 0, S = +6.",
    year: 2021,
  },
  {
    questionText: "Which of the following is an example of a physical change?",
    options: ["Burning wood", "Rusting iron", "Melting ice", "Digesting food"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Physical and Chemical Changes",
    explanation:
      "Melting ice is a physical change because only the state of matter changes. No new substance is formed.",
    year: 2020,
  },
  {
    questionText: "What is the molar mass of NaCl?",
    options: ["23 g/mol", "35.5 g/mol", "58.5 g/mol", "77 g/mol"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Molar Mass Calculations",
    explanation: "Molar mass of NaCl = Na(23) + Cl(35.5) = 58.5 g/mol",
    year: 2018,
  },
  {
    questionText:
      "Which type of reaction involves the combination of two substances to form one product?",
    options: [
      "Decomposition",
      "Synthesis",
      "Single displacement",
      "Double displacement",
    ],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Types of Chemical Reactions",
    explanation:
      "A synthesis (combination) reaction: A + B → AB. Two or more reactants combine to form a single product.",
    year: 2019,
  },
  {
    questionText: "What is the number of moles in 44 g of CO₂? (C=12, O=16)",
    options: ["0.5 mol", "1 mol", "1.5 mol", "2 mol"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Mole Calculations",
    explanation:
      "Molar mass of CO₂ = 12 + 2(16) = 44 g/mol. Number of moles = mass/molar mass = 44/44 = 1 mol.",
    year: 2021,
  },
  {
    questionText: "Which of the following is a noble gas?",
    options: ["Nitrogen", "Oxygen", "Argon", "Chlorine"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Periodic Table - Groups",
    explanation:
      "Argon (Ar) is a noble gas in Group 18 of the periodic table. Noble gases have full outer electron shells.",
    year: 2020,
  },
  {
    questionText:
      "What happens to the rate of a chemical reaction when temperature is increased?",
    options: [
      "Rate decreases",
      "Rate increases",
      "Rate remains unchanged",
      "Reaction stops",
    ],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Reaction Rates",
    explanation:
      "Increasing temperature increases the kinetic energy of particles, leading to more frequent and energetic collisions, thus increasing reaction rate.",
    year: 2018,
  },
  {
    questionText:
      "Which law states that gases at the same temperature and pressure contain equal numbers of molecules?",
    options: ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Dalton's Law"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Gas Laws",
    explanation:
      "Avogadro's Law states that equal volumes of all gases at the same temperature and pressure contain the same number of molecules.",
    year: 2019,
  },
  {
    questionText:
      "What is the product of the reaction between an acid and a base?",
    options: [
      "Acid + Gas",
      "Salt + Water",
      "Oxide + Hydrogen",
      "Base + Hydrogen",
    ],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Neutralization Reactions",
    explanation:
      "When an acid reacts with a base (neutralization reaction), the products are salt and water: Acid + Base → Salt + Water.",
    year: 2021,
  },
  {
    questionText: "Which functional group is present in alcohols?",
    options: ["-COOH", "-CHO", "-OH", "-NH₂"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Organic Chemistry",
    explanation:
      "Alcohols contain the hydroxyl functional group (-OH) attached to a carbon atom.",
    year: 2020,
  },
  {
    questionText:
      "What is the electronic configuration of Sodium (Na, atomic number 11)?",
    options: ["2,8,1", "2,8,2", "2,6,1", "2,9"],
    correctAnswer: 0,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Electronic Configuration",
    explanation:
      "Sodium has 11 electrons distributed as: 2 in first shell, 8 in second shell, 1 in third shell = 2,8,1",
    year: 2018,
  },

  // ─── PHYSICS (20 questions) ───────────────────────────────

  {
    questionText: "What is the unit of electric current?",
    options: ["Volt", "Watt", "Ohm", "Ampere"],
    correctAnswer: 3,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Electricity",
    explanation:
      "Electric current is measured in Amperes (A). Current is the rate of flow of electric charge.",
    year: 2019,
  },
  {
    questionText: "What is the speed of light in a vacuum?",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10¹² m/s"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Waves and Optics",
    explanation:
      "The speed of light in a vacuum is approximately 3 × 10⁸ m/s (300,000 km/s).",
    year: 2020,
  },
  {
    questionText: "According to Newton's Second Law, Force equals:",
    options: [
      "mass × velocity",
      "mass × acceleration",
      "mass × distance",
      "mass × time",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Newton's Laws of Motion",
    explanation:
      "Newton's Second Law states F = ma, where F is force (N), m is mass (kg), and a is acceleration (m/s²).",
    year: 2021,
  },
  {
    questionText: "What is the SI unit of work?",
    options: ["Newton", "Watt", "Joule", "Pascal"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Work, Energy and Power",
    explanation:
      "Work = Force × Distance. The SI unit of work is the Joule (J). 1 J = 1 N × 1 m.",
    year: 2018,
  },
  {
    questionText: "Which type of wave requires a medium to travel?",
    options: ["Light waves", "Radio waves", "Sound waves", "X-rays"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Waves",
    explanation:
      "Sound waves are mechanical waves that require a medium (solid, liquid, or gas) to travel. Light and radio waves are electromagnetic and can travel through vacuum.",
    year: 2019,
  },
  {
    questionText:
      "An object is moving at 20 m/s. If it accelerates at 5 m/s² for 3 seconds, what is its final velocity?",
    options: ["25 m/s", "30 m/s", "35 m/s", "40 m/s"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Kinematics",
    explanation: "Using v = u + at: v = 20 + (5 × 3) = 20 + 15 = 35 m/s",
    year: 2021,
  },
  {
    questionText:
      "What is the relationship between frequency and wavelength of a wave?",
    options: [
      "They are directly proportional",
      "They are inversely proportional",
      "They are equal",
      "They are independent of each other",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Wave Properties",
    explanation:
      "v = fλ. If wave speed is constant, frequency and wavelength are inversely proportional: as frequency increases, wavelength decreases.",
    year: 2020,
  },
  {
    questionText: "What is the gravitational acceleration on Earth's surface?",
    options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11.9 m/s²"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Gravity",
    explanation:
      "The standard acceleration due to gravity on Earth's surface is g = 9.8 m/s² (often approximated as 10 m/s²).",
    year: 2019,
  },
  {
    questionText: "Ohm's Law states that:",
    options: ["V = IR", "V = I/R", "V = I²R", "V = I + R"],
    correctAnswer: 0,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Electricity - Ohm's Law",
    explanation:
      "Ohm's Law: V = IR, where V is voltage (volts), I is current (amperes), and R is resistance (ohms).",
    year: 2021,
  },
  {
    questionText:
      "A 60W bulb is connected to a 220V supply. What is the current flowing through it?",
    options: ["0.18 A", "0.27 A", "0.36 A", "0.45 A"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Electricity - Power",
    explanation: "P = VI, so I = P/V = 60/220 ≈ 0.27 A",
    year: 2018,
  },
  {
    questionText:
      "Which phenomenon explains why a pencil appears bent when placed in water?",
    options: ["Reflection", "Refraction", "Diffraction", "Interference"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Optics - Refraction",
    explanation:
      "Refraction is the bending of light as it passes from one medium to another with different optical density. This makes the pencil appear bent at the water surface.",
    year: 2020,
  },
  {
    questionText:
      "What is kinetic energy of an object of mass 2 kg moving at 4 m/s?",
    options: ["8 J", "12 J", "16 J", "20 J"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Energy",
    explanation: "KE = ½mv² = ½ × 2 × 4² = ½ × 2 × 16 = 16 J",
    year: 2019,
  },
  {
    questionText:
      "Which law states that every action has an equal and opposite reaction?",
    options: [
      "Newton's First Law",
      "Newton's Second Law",
      "Newton's Third Law",
      "Hooke's Law",
    ],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Newton's Laws",
    explanation:
      "Newton's Third Law of Motion: For every action, there is an equal and opposite reaction.",
    year: 2021,
  },
  {
    questionText: "What is the unit of resistance?",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Electricity",
    explanation:
      "Electrical resistance is measured in Ohms (Ω), named after German physicist Georg Simon Ohm.",
    year: 2020,
  },
  {
    questionText: "The phenomenon of total internal reflection is used in:",
    options: ["Microscopes", "Optical fibres", "Periscopes", "Telescopes"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Optics",
    explanation:
      "Optical fibres use total internal reflection to transmit light signals over long distances with minimal loss.",
    year: 2018,
  },
  {
    questionText: "What is the SI unit of power?",
    options: ["Joule", "Newton", "Watt", "Pascal"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Work, Energy and Power",
    explanation:
      "Power is the rate of doing work. The SI unit of power is the Watt (W). 1 W = 1 J/s.",
    year: 2019,
  },
  {
    questionText: "Which of the following is NOT an electromagnetic wave?",
    options: ["Gamma rays", "X-rays", "Sound waves", "Ultraviolet rays"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Electromagnetic Spectrum",
    explanation:
      "Sound waves are mechanical waves that require a medium. All others (gamma, X-rays, UV) are electromagnetic waves that can travel through vacuum.",
    year: 2021,
  },
  {
    questionText:
      "A transformer has 100 turns in primary and 500 turns in secondary. If primary voltage is 20V, what is secondary voltage?",
    options: ["4V", "20V", "100V", "200V"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Electromagnetic Induction",
    explanation:
      "Vs/Vp = Ns/Np. So Vs = Vp × (Ns/Np) = 20 × (500/100) = 20 × 5 = 100V",
    year: 2020,
  },
  {
    questionText: "What type of charge does an electron carry?",
    options: ["Positive", "Negative", "Neutral", "Variable"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Atomic Physics",
    explanation:
      "An electron carries a negative charge of -1.6 × 10⁻¹⁹ coulombs.",
    year: 2018,
  },
  {
    questionText: "What is the law of conservation of energy?",
    options: [
      "Energy can be created but not destroyed",
      "Energy can be destroyed but not created",
      "Energy can neither be created nor destroyed, only converted",
      "Energy is always lost as heat",
    ],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Energy",
    explanation:
      "The law of conservation of energy states that energy cannot be created or destroyed, only transformed from one form to another.",
    year: 2019,
  },

  // ─── CIVICS (20 questions) ────────────────────────────────

  {
    questionText: "What is the capital city of Ethiopia?",
    options: ["Dire Dawa", "Hawassa", "Addis Ababa", "Bahir Dar"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Geography of Ethiopia",
    explanation:
      'Addis Ababa is the capital and largest city of Ethiopia. Its name means "New Flower" in Amharic.',
    year: 2019,
  },
  {
    questionText:
      "In what year did Ethiopia adopt its current Federal Democratic Republic Constitution?",
    options: ["1991", "1993", "1995", "1997"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Constitution",
    explanation:
      "The Constitution of the Federal Democratic Republic of Ethiopia (FDRE) was ratified and came into force on August 22, 1995.",
    year: 2020,
  },
  {
    questionText: "How many regional states does Ethiopia have?",
    options: ["9", "10", "11", "12"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government Structure",
    explanation:
      "Ethiopia currently has 11 regional states and 2 chartered cities (Addis Ababa and Dire Dawa).",
    year: 2021,
  },
  {
    questionText:
      "Which international organization has its headquarters in Addis Ababa?",
    options: [
      "United Nations",
      "African Union",
      "World Trade Organization",
      "NATO",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "International Organizations",
    explanation:
      "The African Union (AU) has its headquarters in Addis Ababa, Ethiopia. It was established in 2002.",
    year: 2018,
  },
  {
    questionText: "What is the highest law of the land in Ethiopia?",
    options: [
      "The Civil Code",
      "The Criminal Code",
      "The Constitution",
      "Parliamentary Acts",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Rule of Law",
    explanation:
      "The Constitution is the supreme law of Ethiopia. All other laws must conform to it.",
    year: 2019,
  },
  {
    questionText:
      "Which of the following is a fundamental right guaranteed by the Ethiopian Constitution?",
    options: [
      "Right to free housing",
      "Right to free education up to university",
      "Right to life",
      "Right to a government job",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Human Rights and Constitution",
    explanation:
      "The right to life is a fundamental human right protected under Article 15 of the Ethiopian Constitution.",
    year: 2021,
  },
  {
    questionText: 'What does "democracy" mean?',
    options: [
      "Rule by the military",
      "Rule by one person",
      "Rule by the people",
      "Rule by religious leaders",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Democracy and Governance",
    explanation:
      'Democracy comes from Greek words "demos" (people) and "kratos" (rule). It means a system of government where citizens exercise power by voting.',
    year: 2020,
  },
  {
    questionText:
      "What is the role of the House of Peoples' Representatives in Ethiopia?",
    options: [
      "Enforce laws",
      "Make and pass laws",
      "Interpret laws",
      "Execute government programs",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "The House of Peoples' Representatives is the legislative body (parliament) of Ethiopia responsible for making and passing federal laws.",
    year: 2018,
  },
  {
    questionText: "Which of the following best describes corruption?",
    options: [
      "Using public office for personal gain",
      "Paying taxes honestly",
      "Voting in elections",
      "Following government regulations",
    ],
    correctAnswer: 0,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Good Governance",
    explanation:
      "Corruption is the abuse of entrusted power for private gain. It undermines democracy, rule of law, and economic development.",
    year: 2021,
  },
  {
    questionText: "What is the Universal Declaration of Human Rights?",
    options: [
      "An African treaty on human rights",
      "A document adopted by the UN in 1948 listing fundamental human rights",
      "The Ethiopian Constitution",
      "A regional agreement on trade",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Human Rights",
    explanation:
      "The UDHR was adopted by the UN General Assembly on December 10, 1948. It lists 30 articles covering fundamental rights and freedoms of all people.",
    year: 2019,
  },
  {
    questionText: 'What is the meaning of the term "sovereignty"?',
    options: [
      "The right of citizens to vote",
      "The supreme power of a state to govern itself",
      "The authority of religious leaders",
      "The power of international organizations",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Political Science Concepts",
    explanation:
      "Sovereignty refers to the supreme authority of a state to govern itself without external interference.",
    year: 2020,
  },
  {
    questionText:
      "Which branch of government is responsible for interpreting laws in Ethiopia?",
    options: [
      "Legislative branch",
      "Executive branch",
      "Judicial branch",
      "Federal branch",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Separation of Powers",
    explanation:
      "The judicial branch (courts) interprets laws and ensures they comply with the constitution. This is one of the three branches of government.",
    year: 2018,
  },
  {
    questionText: "What is civic education primarily concerned with?",
    options: [
      "Learning about science and technology",
      "Understanding rights, responsibilities, and participation in society",
      "Studying the history of ancient civilizations",
      "Learning foreign languages",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Civic Education",
    explanation:
      "Civic education teaches citizens about their rights, responsibilities, and how to participate effectively in their community and government.",
    year: 2021,
  },
  {
    questionText:
      "What year did Ethiopia become a member of the United Nations?",
    options: ["1945", "1950", "1955", "1960"],
    correctAnswer: 0,
    subject: "civics",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Ethiopia and International Relations",
    explanation:
      "Ethiopia was one of the founding members of the United Nations, joining in 1945 when the UN was established.",
    year: 2019,
  },
  {
    questionText: "Which of the following is NOT a pillar of good governance?",
    options: ["Transparency", "Accountability", "Corruption", "Rule of law"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Good Governance",
    explanation:
      "The pillars of good governance include transparency, accountability, rule of law, participation, equity, and effectiveness. Corruption is the opposite of good governance.",
    year: 2020,
  },
  {
    questionText: "What is the purpose of separation of powers in government?",
    options: [
      "To slow down government decision-making",
      "To prevent any one branch from having too much power",
      "To give more power to the military",
      "To allow the president to control everything",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Separation of Powers",
    explanation:
      "Separation of powers divides government into legislative, executive, and judicial branches with checks and balances to prevent abuse of power.",
    year: 2018,
  },
  {
    questionText: "What is federalism?",
    options: [
      "A system where all power is with the central government",
      "A system where power is divided between central and regional governments",
      "A system of military rule",
      "A system where the church controls the government",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Types of Government",
    explanation:
      "Federalism is a system of government where power is constitutionally divided between a central (federal) government and regional (state) governments.",
    year: 2021,
  },
  {
    questionText:
      "Which document protects the rights of children internationally?",
    options: [
      "Universal Declaration of Human Rights",
      "African Charter on Human Rights",
      "UN Convention on the Rights of the Child",
      "Geneva Convention",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "International Human Rights",
    explanation:
      "The UN Convention on the Rights of the Child (UNCRC), adopted in 1989, is the most widely ratified international human rights treaty protecting children.",
    year: 2019,
  },
  {
    questionText:
      "What is the primary duty of a citizen in a democratic country?",
    options: [
      "Paying taxes only",
      "Participating in elections and civic life",
      "Obeying only laws they agree with",
      "Following only religious laws",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Citizenship and Civic Duty",
    explanation:
      "Active participation in elections and civic life is a primary duty of citizens in a democracy. This includes voting, obeying laws, paying taxes, and community service.",
    year: 2020,
  },
  {
    questionText:
      "Ethiopia's flag consists of which three colors from top to bottom?",
    options: [
      "Red, Yellow, Green",
      "Green, Yellow, Red",
      "Yellow, Green, Red",
      "Red, Green, Yellow",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Ethiopian National Symbols",
    explanation:
      "The Ethiopian flag has three horizontal stripes: Green (top), Yellow (middle), and Red (bottom), with a blue circle and star emblem in the center.",
    year: 2021,
  },
];

module.exports = questions;
