const questions = [
  // ─── MATHEMATICS (20 questions) ───────────────────────────

  {
    questionText: "What is the value of x if 2x + 6 = 14?",
    options: ["3", "4", "6", "8"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Linear Equations",
    explanation: "2x = 14 - 6 = 8, therefore x = 4",
    year: 2020,
  },
  {
    questionText: "If f(x) = x² + 3x - 4, what is f(2)?",
    options: ["4", "6", "8", "10"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Functions",
    explanation: "f(2) = (2)² + 3(2) - 4 = 4 + 6 - 4 = 6",
    year: 2021,
  },
  {
    questionText:
      "What is the slope of the line passing through points (2, 3) and (4, 7)?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Coordinate Geometry",
    explanation: "slope = (y2 - y1) / (x2 - x1) = (7 - 3) / (4 - 2) = 4/2 = 2",
    year: 2019,
  },
  {
    questionText: "What is the sum of the interior angles of a hexagon?",
    options: ["540°", "620°", "720°", "800°"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Geometry",
    explanation:
      "Sum of interior angles = (n - 2) × 180° = (6 - 2) × 180° = 720°",
    year: 2020,
  },
  {
    questionText: "What is the value of log₁₀(1000)?",
    options: ["2", "3", "4", "10"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Logarithms",
    explanation: "log₁₀(1000) = log₁₀(10³) = 3",
    year: 2018,
  },
  {
    questionText: "Solve for x: x² - 5x + 6 = 0",
    options: [
      "x = 1, x = 6",
      "x = 2, x = 3",
      "x = -2, x = -3",
      "x = -1, x = 6",
    ],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Quadratic Equations",
    explanation: "Factoring: (x - 2)(x - 3) = 0, so x = 2 or x = 3",
    year: 2021,
  },
  {
    questionText:
      "What is the area of a circle with radius 7 cm? (Use π = 22/7)",
    options: ["44 cm²", "154 cm²", "176 cm²", "308 cm²"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Circle",
    explanation: "Area = πr² = (22/7) × 7 × 7 = 22 × 7 = 154 cm²",
    year: 2019,
  },
  {
    questionText: "If sin θ = 3/5, what is cos θ? (θ is in the first quadrant)",
    options: ["3/4", "4/5", "5/3", "5/4"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Trigonometry",
    explanation:
      "Using sin²θ + cos²θ = 1: cos²θ = 1 - 9/25 = 16/25, cos θ = 4/5",
    year: 2022,
  },
  {
    questionText:
      "What is the 10th term of the arithmetic sequence 3, 7, 11, 15, ...?",
    options: ["35", "39", "43", "47"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Sequences and Series",
    explanation: "a₁₀ = a₁ + (n-1)d = 3 + (10-1)×4 = 3 + 36 = 39",
    year: 2020,
  },
  {
    questionText: "What is the determinant of the matrix [[2, 3], [1, 4]]?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 0,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Matrices",
    explanation: "det = (2×4) - (3×1) = 8 - 3 = 5",
    year: 2021,
  },
  {
    questionText:
      "What is the probability of getting a head when flipping a fair coin?",
    options: ["1/4", "1/3", "1/2", "2/3"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Probability",
    explanation: "A fair coin has 2 equal outcomes. P(head) = 1/2",
    year: 2018,
  },
  {
    questionText: "What is the value of 5! (5 factorial)?",
    options: ["25", "60", "100", "120"],
    correctAnswer: 3,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Permutations and Combinations",
    explanation: "5! = 5 × 4 × 3 × 2 × 1 = 120",
    year: 2019,
  },
  {
    questionText: "If the mean of 5 numbers is 12, what is their sum?",
    options: ["17", "36", "60", "72"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Statistics",
    explanation: "Mean = Sum/Count. Sum = Mean × Count = 12 × 5 = 60",
    year: 2020,
  },
  {
    questionText: "What is the derivative of f(x) = x³ + 2x² - 5x + 1?",
    options: ["3x² + 4x - 5", "3x² + 4x + 5", "x² + 4x - 5", "3x + 4"],
    correctAnswer: 0,
    subject: "math",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Calculus - Differentiation",
    explanation: "Using power rule: f'(x) = 3x² + 4x - 5",
    year: 2022,
  },
  {
    questionText: "What is the solution to the inequality 2x - 3 > 7?",
    options: ["x > 2", "x > 5", "x < 5", "x < 2"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Inequalities",
    explanation: "2x > 7 + 3 = 10, therefore x > 5",
    year: 2019,
  },
  {
    questionText: "What is the geometric mean of 4 and 16?",
    options: ["6", "8", "10", "12"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Sequences and Series",
    explanation: "Geometric mean = √(4 × 16) = √64 = 8",
    year: 2021,
  },
  {
    questionText: "How many ways can 4 people be arranged in a line?",
    options: ["4", "12", "16", "24"],
    correctAnswer: 3,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Permutations",
    explanation: "4! = 4 × 3 × 2 × 1 = 24 ways",
    year: 2020,
  },
  {
    questionText: "What is the range of the function f(x) = x² for all real x?",
    options: ["All real numbers", "x ≥ 0", "x > 0", "x ≤ 0"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Functions",
    explanation: "x² is always non-negative for all real x, so range is y ≥ 0",
    year: 2022,
  },
  {
    questionText: "What is the value of tan 45°?",
    options: ["0", "1", "√2", "√3/2"],
    correctAnswer: 1,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Trigonometry",
    explanation: "tan 45° = sin 45° / cos 45° = (√2/2) / (√2/2) = 1",
    year: 2018,
  },
  {
    questionText: "What is the volume of a cube with side length 3 cm?",
    options: ["9 cm³", "18 cm³", "27 cm³", "54 cm³"],
    correctAnswer: 2,
    subject: "math",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Solid Geometry",
    explanation: "Volume of cube = side³ = 3³ = 27 cm³",
    year: 2019,
  },

  // ─── ENGLISH (20 questions) ───────────────────────────────

  {
    questionText: "Choose the word that is closest in meaning to DILIGENT:",
    options: ["Lazy", "Hardworking", "Clever", "Honest"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Vocabulary - Synonyms",
    explanation:
      "Diligent means showing care and effort in work — same as hardworking",
    year: 2020,
  },
  {
    questionText: "Which sentence is grammatically correct?",
    options: [
      "She don't know the answer",
      "They was going to school",
      "He has been studying for 3 hours",
      "We is happy today",
    ],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Tenses",
    explanation:
      "Present perfect continuous: Subject + has/have + been + verb-ing",
    year: 2021,
  },
  {
    questionText: "Choose the antonym of ABUNDANT:",
    options: ["Plentiful", "Scarce", "Rich", "Excessive"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Vocabulary - Antonyms",
    explanation:
      "Abundant means plentiful/more than enough. Its antonym is scarce meaning not enough",
    year: 2019,
  },
  {
    questionText:
      'Which word correctly completes the sentence: "The student _____ her homework before dinner"?',
    options: ["finish", "finishes", "finished", "finishing"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Verb Tenses",
    explanation:
      "Past tense is needed here as the action was completed before another past event",
    year: 2020,
  },
  {
    questionText: 'What is the plural form of "criterion"?',
    options: ["criterions", "criterias", "criteria", "criterions"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Plurals",
    explanation: "Criterion is a Latin word. Its plural is criteria",
    year: 2022,
  },
  {
    questionText:
      'Choose the correct passive form of: "The teacher teaches the students"',
    options: [
      "The students are taught by the teacher",
      "The students were taught by the teacher",
      "The students teach by the teacher",
      "The students is taught by the teacher",
    ],
    correctAnswer: 0,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Passive Voice",
    explanation:
      "Passive voice: object + is/are + past participle + by + subject",
    year: 2021,
  },
  {
    questionText:
      'Which figure of speech is used in: "The wind whispered through the trees"?',
    options: ["Simile", "Metaphor", "Personification", "Hyperbole"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Literary Devices",
    explanation:
      "Personification gives human qualities (whispering) to non-human things (wind)",
    year: 2020,
  },
  {
    questionText:
      'Choose the word that best completes: "Despite the rain, the children _____ outside"',
    options: ["playing", "played", "plays", "to play"],
    correctAnswer: 1,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Verb Forms",
    explanation: 'Past tense "played" is correct for a completed action',
    year: 2019,
  },
  {
    questionText: 'What does the idiom "break the ice" mean?',
    options: [
      "To literally break frozen water",
      "To start a conversation in a social situation",
      "To cause trouble",
      "To cool down a situation",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Idioms and Phrases",
    explanation:
      '"Break the ice" means to do or say something to relieve tension in a social situation',
    year: 2021,
  },
  {
    questionText: "Choose the correctly punctuated sentence:",
    options: [
      "Its a beautiful day isnt it",
      "It's a beautiful day, isn't it?",
      "Its a beautiful day, isnt it?",
      "It's a beautiful day isnt it.",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Punctuation",
    explanation:
      "It's = it is (apostrophe for contraction), isn't = is not, question mark at end",
    year: 2022,
  },
  {
    questionText: "Which of the following is a compound sentence?",
    options: [
      "She studied hard for the exam",
      "Although she was tired, she kept studying",
      "She studied hard, and she passed the exam",
      "Studying hard is important",
    ],
    correctAnswer: 2,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Sentence Structure",
    explanation:
      "A compound sentence has two independent clauses joined by a coordinating conjunction (and)",
    year: 2020,
  },
  {
    questionText:
      'What is the meaning of the prefix "mis-" in the word "misunderstand"?',
    options: ["Again", "Not", "Wrongly", "Before"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Word Formation",
    explanation:
      'The prefix "mis-" means wrongly or badly, as in misunderstand = understand wrongly',
    year: 2019,
  },
  {
    questionText:
      "Choose the sentence with the correct subject-verb agreement:",
    options: [
      "The team are playing well",
      "Neither the students nor the teacher are ready",
      "Each of the students have a book",
      "Either the students or the teacher is responsible",
    ],
    correctAnswer: 3,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Grammar - Subject-Verb Agreement",
    explanation:
      'With "either...or", the verb agrees with the subject closest to it (teacher = singular = is)',
    year: 2021,
  },
  {
    questionText: 'What type of noun is "honesty"?',
    options: [
      "Proper noun",
      "Concrete noun",
      "Abstract noun",
      "Collective noun",
    ],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Nouns",
    explanation:
      "Abstract nouns name qualities, ideas, or feelings that cannot be physically touched",
    year: 2020,
  },
  {
    questionText:
      'Choose the correct reported speech: He said, "I am going to school"',
    options: [
      "He said that he is going to school",
      "He said that he was going to school",
      "He said that I was going to school",
      "He said that he will go to school",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Grammar - Reported Speech",
    explanation:
      "In reported speech, present tense (am) changes to past tense (was)",
    year: 2022,
  },
  {
    questionText:
      'Which word is a conjunction in: "I will come if you invite me"?',
    options: ["will", "come", "if", "invite"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Parts of Speech",
    explanation:
      '"If" is a subordinating conjunction that introduces a conditional clause',
    year: 2019,
  },
  {
    questionText: "What is the meaning of AMBIGUOUS?",
    options: [
      "Very clear",
      "Open to more than one interpretation",
      "Completely wrong",
      "Highly important",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Vocabulary",
    explanation:
      "Ambiguous means having more than one possible meaning or interpretation",
    year: 2021,
  },
  {
    questionText: 'Choose the correct comparative form of "good":',
    options: ["gooder", "more good", "better", "best"],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Grammar - Adjectives",
    explanation:
      '"Good" has irregular comparative form "better" and superlative "best"',
    year: 2020,
  },
  {
    questionText: "Which sentence uses the correct article?",
    options: [
      "She is a honest person",
      "She is an honest person",
      "She is the honest person",
      "She is honest person",
    ],
    correctAnswer: 1,
    subject: "english",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Grammar - Articles",
    explanation:
      'Use "an" before words beginning with a vowel sound. "Honest" starts with a silent h, so vowel sound',
    year: 2019,
  },
  {
    questionText: "What is a simile?",
    options: [
      "Giving human qualities to non-human things",
      "An exaggerated statement",
      'A comparison using "like" or "as"',
      "A word that sounds like its meaning",
    ],
    correctAnswer: 2,
    subject: "english",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Literary Devices",
    explanation:
      'A simile directly compares two things using "like" or "as", e.g. "brave as a lion"',
    year: 2022,
  },

  // ─── BIOLOGY (20 questions) ───────────────────────────────

  {
    questionText: "Which organelle is known as the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Apparatus"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Cell Biology",
    explanation: "Mitochondria produce ATP energy through cellular respiration",
    year: 2020,
  },
  {
    questionText: "What type of blood cells carry oxygen throughout the body?",
    options: ["White blood cells", "Platelets", "Red blood cells", "Plasma"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Human Biology - Blood",
    explanation:
      "Red blood cells (erythrocytes) contain hemoglobin which binds and carries oxygen",
    year: 2019,
  },
  {
    questionText: "What is the process by which plants make their own food?",
    options: ["Respiration", "Transpiration", "Photosynthesis", "Osmosis"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Plant Biology",
    explanation:
      "Photosynthesis uses sunlight, CO₂, and water to produce glucose and oxygen",
    year: 2021,
  },
  {
    questionText: "What is the basic unit of heredity?",
    options: ["Cell", "Chromosome", "Gene", "DNA"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Genetics",
    explanation:
      "A gene is a segment of DNA that codes for a specific protein or trait",
    year: 2020,
  },
  {
    questionText: "Which part of the brain controls balance and coordination?",
    options: ["Cerebrum", "Cerebellum", "Medulla oblongata", "Hypothalamus"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Nervous System",
    explanation:
      "The cerebellum coordinates voluntary movements and maintains balance",
    year: 2022,
  },
  {
    questionText: "What happens during mitosis?",
    options: [
      "A cell produces gametes with half the chromosomes",
      "A cell divides into two identical daughter cells",
      "A cell undergoes fertilization",
      "A cell produces energy",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Cell Division",
    explanation:
      "Mitosis is cell division that produces two genetically identical daughter cells",
    year: 2021,
  },
  {
    questionText: "What is the function of the kidneys?",
    options: [
      "To produce insulin",
      "To filter blood and produce urine",
      "To produce red blood cells",
      "To break down food",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Excretory System",
    explanation:
      "Kidneys filter waste products from the blood and excrete them as urine",
    year: 2020,
  },
  {
    questionText: "Which hormone regulates blood sugar levels?",
    options: ["Adrenaline", "Thyroxine", "Insulin", "Estrogen"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Endocrine System",
    explanation:
      "Insulin produced by the pancreas lowers blood glucose by promoting cellular uptake",
    year: 2019,
  },
  {
    questionText: "What is the role of ribosomes in cells?",
    options: [
      "Energy production",
      "Protein synthesis",
      "DNA replication",
      "Lipid storage",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Cell Biology",
    explanation:
      "Ribosomes are sites of protein synthesis, translating mRNA into proteins",
    year: 2021,
  },
  {
    questionText: "What is osmosis?",
    options: [
      "Movement of solutes from high to low concentration",
      "Movement of water from high to low water potential through a semi-permeable membrane",
      "Active transport of molecules against concentration gradient",
      "Movement of gases across cell membranes",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Transport in Cells",
    explanation:
      "Osmosis is the passive movement of water through a semi-permeable membrane",
    year: 2022,
  },
  {
    questionText: "Which blood group is known as the universal donor?",
    options: ["A", "B", "AB", "O"],
    correctAnswer: 3,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Human Biology - Blood",
    explanation:
      "Blood group O negative has no A, B, or Rh antigens so it can be donated to anyone",
    year: 2020,
  },
  {
    questionText: "What is the function of chlorophyll?",
    options: [
      "Absorb water from soil",
      "Absorb light energy for photosynthesis",
      "Transport nutrients in plants",
      "Regulate plant growth",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Plant Biology",
    explanation:
      "Chlorophyll is the green pigment that absorbs light energy used in photosynthesis",
    year: 2019,
  },
  {
    questionText: "Which type of reproduction does not require fertilization?",
    options: [
      "Sexual reproduction",
      "Asexual reproduction",
      "Cross-pollination",
      "Meiosis",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Reproduction",
    explanation:
      "Asexual reproduction involves only one parent and no fertilization",
    year: 2021,
  },
  {
    questionText: "What is the chemical formula for glucose?",
    options: ["C₆H₁₂O₆", "C₁₂H₂₂O₁₁", "CO₂", "C₂H₅OH"],
    correctAnswer: 0,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Biochemistry",
    explanation: "Glucose is a simple sugar with the molecular formula C₆H₁₂O₆",
    year: 2022,
  },
  {
    questionText: "What is the role of white blood cells?",
    options: [
      "Carry oxygen",
      "Help blood clot",
      "Fight infection and disease",
      "Transport nutrients",
    ],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Human Biology - Immune System",
    explanation:
      "White blood cells (leukocytes) are part of the immune system that fight pathogens",
    year: 2020,
  },
  {
    questionText:
      "Which part of the plant absorbs water and minerals from the soil?",
    options: ["Leaves", "Stem", "Roots", "Flowers"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Plant Biology",
    explanation:
      "Root hairs increase surface area for absorption of water and dissolved minerals",
    year: 2019,
  },
  {
    questionText: "What is DNA?",
    options: [
      "A type of protein",
      "Deoxyribonucleic acid that carries genetic information",
      "A lipid found in cell membranes",
      "An enzyme that breaks down food",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Genetics",
    explanation:
      "DNA (Deoxyribonucleic acid) is the molecule that carries genetic information in all living organisms",
    year: 2021,
  },
  {
    questionText: "Which organ produces bile?",
    options: ["Stomach", "Pancreas", "Liver", "Gallbladder"],
    correctAnswer: 2,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Digestive System",
    explanation:
      "The liver produces bile which is stored in the gallbladder and used to emulsify fats",
    year: 2022,
  },
  {
    questionText: "What is the normal resting heart rate for adults?",
    options: ["40-50 bpm", "60-100 bpm", "110-130 bpm", "150-180 bpm"],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Circulatory System",
    explanation: "Normal adult resting heart rate is 60-100 beats per minute",
    year: 2020,
  },
  {
    questionText: "What is natural selection?",
    options: [
      "Humans selecting the best crops to grow",
      "The process where organisms with favorable traits survive and reproduce more",
      "Random changes in DNA",
      "Migration of organisms to better environments",
    ],
    correctAnswer: 1,
    subject: "biology",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Evolution",
    explanation:
      "Natural selection: organisms with traits better suited to environment survive and reproduce more",
    year: 2021,
  },

  // ─── CHEMISTRY (20 questions) ─────────────────────────────

  {
    questionText: "What is the chemical symbol for Gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Periodic Table",
    explanation: "Au comes from the Latin word Aurum meaning gold",
    year: 2020,
  },
  {
    questionText: "How many electrons does a Carbon atom have?",
    options: ["4", "6", "8", "12"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Atomic Structure",
    explanation:
      "Carbon has atomic number 6, meaning 6 protons and 6 electrons",
    year: 2019,
  },
  {
    questionText: "What is the pH of a neutral solution?",
    options: ["0", "5", "7", "14"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Acids and Bases",
    explanation: "Pure water and neutral solutions have a pH of 7",
    year: 2021,
  },
  {
    questionText: "Which gas is produced when acids react with metals?",
    options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Chemical Reactions",
    explanation:
      "Acid + Metal → Salt + Hydrogen gas. e.g. Zn + H₂SO₄ → ZnSO₄ + H₂",
    year: 2020,
  },
  {
    questionText: "What is the atomic number of Sodium (Na)?",
    options: ["8", "11", "12", "23"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Periodic Table",
    explanation: "Sodium has atomic number 11, meaning it has 11 protons",
    year: 2022,
  },
  {
    questionText:
      "What type of bond is formed when electrons are shared between atoms?",
    options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Chemical Bonding",
    explanation:
      "Covalent bonds form when atoms share electrons to achieve stable electron configurations",
    year: 2021,
  },
  {
    questionText: "What is the chemical formula for water?",
    options: ["HO", "H₂O", "H₂O₂", "HO₂"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Chemical Formulas",
    explanation:
      "Water consists of 2 hydrogen atoms bonded to 1 oxygen atom: H₂O",
    year: 2019,
  },
  {
    questionText: "Which of the following is a noble gas?",
    options: ["Oxygen", "Nitrogen", "Argon", "Chlorine"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Periodic Table",
    explanation:
      "Noble gases (Group 18) include Helium, Neon, Argon, Krypton, Xenon, and Radon",
    year: 2020,
  },
  {
    questionText: "What is the law of conservation of mass?",
    options: [
      "Mass can be created but not destroyed",
      "Mass is always lost in chemical reactions",
      "The total mass of reactants equals the total mass of products",
      "Mass increases as temperature increases",
    ],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Chemical Reactions",
    explanation:
      "Matter is neither created nor destroyed in a chemical reaction; it changes form",
    year: 2021,
  },
  {
    questionText: "What is an acid according to Arrhenius theory?",
    options: [
      "A substance that accepts protons",
      "A substance that donates electrons",
      "A substance that produces H⁺ ions in water",
      "A substance that produces OH⁻ ions",
    ],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Acids and Bases",
    explanation:
      "Arrhenius acids ionize in water to produce hydrogen ions (H⁺)",
    year: 2022,
  },
  {
    questionText: "What is the valency of oxygen?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Chemical Bonding",
    explanation:
      "Oxygen has 6 valence electrons and needs 2 more to complete its outer shell, so valency = 2",
    year: 2020,
  },
  {
    questionText:
      "Which process separates a mixture of liquids with different boiling points?",
    options: ["Filtration", "Evaporation", "Distillation", "Crystallization"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Separation Techniques",
    explanation:
      "Distillation separates liquids by exploiting differences in boiling points",
    year: 2019,
  },
  {
    questionText: "What is the oxidation state of oxygen in most compounds?",
    options: ["+1", "+2", "-1", "-2"],
    correctAnswer: 3,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Oxidation and Reduction",
    explanation:
      "Oxygen typically has an oxidation state of -2 in most compounds",
    year: 2021,
  },
  {
    questionText: "What is an isotope?",
    options: [
      "Atoms of different elements with the same mass",
      "Atoms of the same element with different numbers of neutrons",
      "Atoms with the same number of protons and electrons",
      "Different forms of the same compound",
    ],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Atomic Structure",
    explanation:
      "Isotopes are atoms of the same element with the same proton number but different neutron numbers",
    year: 2022,
  },
  {
    questionText: "What is the chemical formula for sulfuric acid?",
    options: ["HCl", "HNO₃", "H₂SO₄", "H₃PO₄"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Acids and Bases",
    explanation:
      "Sulfuric acid has the formula H₂SO₄ - it is a strong diprotic acid",
    year: 2020,
  },
  {
    questionText: "What happens in an exothermic reaction?",
    options: [
      "Energy is absorbed from the surroundings",
      "Energy is released to the surroundings",
      "No energy change occurs",
      "Temperature decreases",
    ],
    correctAnswer: 1,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Thermochemistry",
    explanation:
      "Exothermic reactions release energy (heat) to surroundings, causing temperature to rise",
    year: 2021,
  },
  {
    questionText: "Which element is the most abundant in the Earth's crust?",
    options: ["Silicon", "Iron", "Oxygen", "Aluminum"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Environmental Chemistry",
    explanation: "Oxygen makes up about 46% of the Earth's crust by mass",
    year: 2019,
  },
  {
    questionText: "What is Avogadro's number?",
    options: ["6.022 × 10²³", "3.14 × 10⁸", "9.8 × 10²", "1.6 × 10⁻¹⁹"],
    correctAnswer: 0,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "The Mole",
    explanation:
      "Avogadro's number (6.022 × 10²³) is the number of particles in one mole of a substance",
    year: 2022,
  },
  {
    questionText: "What type of reaction is: NaOH + HCl → NaCl + H₂O?",
    options: ["Decomposition", "Combustion", "Neutralization", "Displacement"],
    correctAnswer: 2,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Chemical Reactions",
    explanation:
      "A neutralization reaction occurs when an acid reacts with a base to form salt and water",
    year: 2020,
  },
  {
    questionText:
      "What is the electronic configuration of Sodium (Na, atomic number 11)?",
    options: ["2, 8, 1", "2, 8, 3", "2, 9", "2, 8, 2, 1"],
    correctAnswer: 0,
    subject: "chemistry",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Atomic Structure",
    explanation:
      "Na (Z=11): 2 electrons in first shell, 8 in second, 1 in third = 2,8,1",
    year: 2021,
  },

  // ─── PHYSICS (20 questions) ───────────────────────────────

  {
    questionText: "What is the unit of electric current?",
    options: ["Volt", "Watt", "Ohm", "Ampere"],
    correctAnswer: 3,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Electricity",
    explanation:
      "Electric current is measured in Amperes (A), named after André-Marie Ampère",
    year: 2020,
  },
  {
    questionText: "What is the speed of light in a vacuum?",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10¹² m/s"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Light and Optics",
    explanation:
      "The speed of light in vacuum is approximately 3 × 10⁸ m/s (300,000 km/s)",
    year: 2019,
  },
  {
    questionText: "According to Newton's second law, force equals:",
    options: [
      "mass × velocity",
      "mass × acceleration",
      "mass × distance",
      "velocity × time",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Newton's Laws",
    explanation: "Newton's second law: F = ma (Force = mass × acceleration)",
    year: 2021,
  },
  {
    questionText: "What is the SI unit of energy?",
    options: ["Watt", "Newton", "Joule", "Pascal"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Work and Energy",
    explanation:
      "The SI unit of energy is the Joule (J), named after James Prescott Joule",
    year: 2020,
  },
  {
    questionText: "What is Ohm's law?",
    options: ["V = IR", "P = IV", "F = ma", "E = mc²"],
    correctAnswer: 0,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Electricity",
    explanation:
      "Ohm's law states V = IR where V is voltage, I is current, R is resistance",
    year: 2022,
  },
  {
    questionText: "What type of wave is sound?",
    options: [
      "Transverse wave",
      "Longitudinal wave",
      "Electromagnetic wave",
      "Surface wave",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Waves",
    explanation:
      "Sound is a longitudinal wave where particles vibrate parallel to wave direction",
    year: 2021,
  },
  {
    questionText: "What is the acceleration due to gravity on Earth?",
    options: ["8.9 m/s²", "9.8 m/s²", "10.5 m/s²", "11.2 m/s²"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Gravity",
    explanation:
      "The acceleration due to gravity on Earth's surface is approximately 9.8 m/s²",
    year: 2019,
  },
  {
    questionText: "What is the law of conservation of energy?",
    options: [
      "Energy can be created from nothing",
      "Energy can be destroyed completely",
      "Energy cannot be created or destroyed, only transformed",
      "Energy always increases in a closed system",
    ],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Work and Energy",
    explanation:
      "The total energy in a closed system remains constant; it only changes form",
    year: 2020,
  },
  {
    questionText: "What is the formula for kinetic energy?",
    options: ["KE = mgh", "KE = ½mv²", "KE = mv", "KE = Fd"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Work and Energy",
    explanation: "Kinetic energy = ½ × mass × velocity² = ½mv²",
    year: 2021,
  },
  {
    questionText:
      "Which phenomenon explains why a straw appears bent in water?",
    options: ["Reflection", "Diffraction", "Refraction", "Interference"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Light and Optics",
    explanation:
      "Refraction is the bending of light as it passes from one medium to another",
    year: 2022,
  },
  {
    questionText: "What is electric power?",
    options: ["P = V/I", "P = VI", "P = V²I", "P = I/V"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Electricity",
    explanation: "Electric power P = VI (voltage × current), measured in Watts",
    year: 2020,
  },
  {
    questionText:
      "What is the frequency of a wave that has a period of 0.02 seconds?",
    options: ["20 Hz", "50 Hz", "100 Hz", "200 Hz"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Waves",
    explanation: "Frequency = 1/Period = 1/0.02 = 50 Hz",
    year: 2019,
  },
  {
    questionText: "What is the principle of moments?",
    options: [
      "For equilibrium, clockwise moments equal anticlockwise moments",
      "Force equals mass times acceleration",
      "Action and reaction are equal and opposite",
      "Energy is conserved in all processes",
    ],
    correctAnswer: 0,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Turning Effects",
    explanation:
      "For a body in equilibrium, sum of clockwise moments = sum of anticlockwise moments",
    year: 2021,
  },
  {
    questionText: "What is nuclear fission?",
    options: [
      "Two light nuclei combine to form a heavier nucleus",
      "A heavy nucleus splits into two smaller nuclei releasing energy",
      "An electron is emitted from a nucleus",
      "A proton is converted to a neutron",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Nuclear Physics",
    explanation:
      "Nuclear fission splits a heavy nucleus (like uranium) into smaller nuclei with release of energy",
    year: 2022,
  },
  {
    questionText: "What is the unit of pressure?",
    options: ["Newton", "Joule", "Pascal", "Watt"],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Pressure",
    explanation: "Pressure is measured in Pascals (Pa) where 1 Pa = 1 N/m²",
    year: 2020,
  },
  {
    questionText:
      "What is the relationship between wavelength, frequency, and wave speed?",
    options: ["v = λ/f", "v = λf", "v = f/λ", "λ = v²f"],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Waves",
    explanation: "Wave speed (v) = wavelength (λ) × frequency (f)",
    year: 2019,
  },
  {
    questionText: "What does a transformer do?",
    options: [
      "Converts AC to DC",
      "Converts DC to AC",
      "Changes the voltage of AC electricity",
      "Stores electrical energy",
    ],
    correctAnswer: 2,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Electromagnetism",
    explanation:
      "A transformer increases or decreases AC voltage using electromagnetic induction",
    year: 2021,
  },
  {
    questionText: "Which type of radiation is stopped by a sheet of paper?",
    options: ["Alpha radiation", "Beta radiation", "Gamma radiation", "X-rays"],
    correctAnswer: 0,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Nuclear Physics",
    explanation:
      "Alpha particles are the least penetrating and can be stopped by paper or skin",
    year: 2022,
  },
  {
    questionText: "What is terminal velocity?",
    options: [
      "The maximum speed of light",
      "The constant speed when driving forces equal resistance forces",
      "The speed at the end of acceleration",
      "The minimum speed needed to escape Earth's gravity",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Forces and Motion",
    explanation:
      "Terminal velocity is reached when gravitational force equals air resistance, resulting in zero acceleration",
    year: 2020,
  },
  {
    questionText: "Einstein's famous equation E = mc² means:",
    options: [
      "Energy equals mass times the speed of light",
      "Energy equals mass times the square of the speed of light",
      "Energy equals mass divided by the speed of light",
      "Energy equals mass plus the speed of light squared",
    ],
    correctAnswer: 1,
    subject: "physics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Modern Physics",
    explanation:
      "E = mc² shows mass-energy equivalence where c is the speed of light (3×10⁸ m/s)",
    year: 2019,
  },

  // ─── CIVICS (20 questions) ────────────────────────────────

  {
    questionText: "In what year did Ethiopia adopt its current constitution?",
    options: ["1991", "1994", "1995", "2000"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Constitution",
    explanation:
      "The FDRE Constitution was ratified on August 22, 1995 and came into force December 8, 1995",
    year: 2020,
  },
  {
    questionText: "What does FDRE stand for?",
    options: [
      "Federal Democratic Republic of Ethiopia",
      "Free Democratic Republic of Ethiopia",
      "Federal Development Republic of Ethiopia",
      "Foundation for Democratic Rights in Ethiopia",
    ],
    correctAnswer: 0,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "FDRE stands for Federal Democratic Republic of Ethiopia, established in 1995",
    year: 2019,
  },
  {
    questionText: "How many regional states does Ethiopia have?",
    options: ["9", "10", "11", "12"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "Ethiopia currently has 11 regional states plus 2 city administrations (Addis Ababa and Dire Dawa)",
    year: 2021,
  },
  {
    questionText: "What is the supreme law of Ethiopia?",
    options: [
      "Criminal Code",
      "The Constitution",
      "The Civil Code",
      "Parliamentary Proclamation",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Ethiopian Constitution",
    explanation:
      "The Constitution of the FDRE is the supreme law of the land; all other laws must conform to it",
    year: 2020,
  },
  {
    questionText: "Which body is the highest legislative organ of Ethiopia?",
    options: [
      "Council of Ministers",
      "House of Federation",
      "House of Peoples' Representatives",
      "Constitutional Inquiry",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "The House of Peoples' Representatives (HPR) is the highest legislative body in Ethiopia",
    year: 2022,
  },
  {
    questionText: "What is democracy?",
    options: [
      "Rule by one person",
      "Rule by a small group of wealthy people",
      "Government by the people, for the people",
      "Rule by the military",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Democracy",
    explanation:
      "Democracy is a system of government where power is vested in the people who rule through elected representatives",
    year: 2019,
  },
  {
    questionText: "Which organization is Ethiopia a founding member of?",
    options: [
      "United Nations",
      "African Union",
      "World Trade Organization",
      "NATO",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "International Relations",
    explanation:
      "Ethiopia was a founding member of the OAU (Organization of African Unity) which became the African Union",
    year: 2021,
  },
  {
    questionText: "What are human rights?",
    options: [
      "Rights given by government and can be taken away",
      "Rights that only wealthy people possess",
      "Inherent rights every person has by virtue of being human",
      "Rights that only citizens of democratic countries have",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Human Rights",
    explanation:
      "Human rights are inherent to all human beings regardless of nationality, sex, ethnicity, religion, or any other status",
    year: 2020,
  },
  {
    questionText: "When was the Universal Declaration of Human Rights adopted?",
    options: ["1945", "1948", "1960", "1975"],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Human Rights",
    explanation:
      "The UDHR was adopted by the UN General Assembly on December 10, 1948",
    year: 2019,
  },
  {
    questionText: "What is federalism?",
    options: [
      "A system where all power belongs to central government",
      "A system where power is divided between central and regional governments",
      "A system where regions have complete independence",
      "A system ruled by a federation of military leaders",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "Federalism divides governmental power between a central (federal) government and constituent units (states/regions)",
    year: 2022,
  },
  {
    questionText: "What is the role of the judiciary in Ethiopia?",
    options: [
      "To make laws",
      "To implement government policies",
      "To interpret laws and administer justice",
      "To elect the president",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian Government",
    explanation:
      "The judiciary interprets laws, resolves disputes, and ensures justice is served independently",
    year: 2021,
  },
  {
    questionText: "What is civil society?",
    options: [
      "The government and its institutions",
      "Organizations and associations outside government and business",
      "The military and police forces",
      "Political parties only",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Civil Society",
    explanation:
      "Civil society includes NGOs, community groups, religious organizations, and other non-governmental organizations",
    year: 2020,
  },
  {
    questionText: "What was the significance of the Battle of Adwa (1896)?",
    options: [
      "Ethiopia lost its independence to Italy",
      "Ethiopia defeated Italy and preserved its sovereignty",
      "Ethiopia became a British colony",
      "Ethiopia joined the Ottoman Empire",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Ethiopian History",
    explanation:
      "The Battle of Adwa was a decisive Ethiopian victory over Italian forces, preserving Ethiopia's independence",
    year: 2022,
  },
  {
    questionText: "What is the separation of powers?",
    options: [
      "Division of the country into regions",
      "Distribution of government power among legislative, executive, and judicial branches",
      "Separation of church and state",
      "Division of resources among citizens",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Government Structure",
    explanation:
      "Separation of powers distributes government authority to prevent concentration of power in one branch",
    year: 2019,
  },
  {
    questionText: "What is the right to vote called?",
    options: ["Civil right", "Political right", "Suffrage", "Franchise right"],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Democracy",
    explanation:
      "Suffrage is the right to vote in political elections; universal suffrage means all adults can vote",
    year: 2021,
  },
  {
    questionText:
      "Which article of the FDRE Constitution protects freedom of expression?",
    options: ["Article 19", "Article 29", "Article 39", "Article 49"],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "hard",
    grade: "Grade 12",
    topic: "Ethiopian Constitution",
    explanation:
      "Article 29 of the FDRE Constitution guarantees freedom of expression and the press",
    year: 2020,
  },
  {
    questionText: "What is corruption?",
    options: [
      "Legal use of public resources",
      "Misuse of entrusted power for private gain",
      "Political disagreement between parties",
      "Economic inequality between citizens",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Good Governance",
    explanation:
      "Corruption involves abuse of power or trust for personal gain, undermining fairness and development",
    year: 2022,
  },
  {
    questionText: "What is the headquarters of the African Union?",
    options: [
      "Nairobi, Kenya",
      "Lagos, Nigeria",
      "Addis Ababa, Ethiopia",
      "Cairo, Egypt",
    ],
    correctAnswer: 2,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "International Relations",
    explanation:
      "The African Union headquarters is located in Addis Ababa, Ethiopia",
    year: 2019,
  },
  {
    questionText: "What is the rule of law?",
    options: [
      "Rule by the strongest person",
      "The principle that everyone including government is subject to the law",
      "Laws made by rulers without public input",
      "Military law applied to civilians",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "medium",
    grade: "Grade 12",
    topic: "Democracy",
    explanation:
      "Rule of law means no one is above the law — all persons and institutions are accountable to law",
    year: 2021,
  },
  {
    questionText: "What is the purpose of elections in a democracy?",
    options: [
      "To give power to wealthy individuals",
      "To allow citizens to choose their representatives and hold them accountable",
      "To maintain the current government in power",
      "To elect judges and military leaders",
    ],
    correctAnswer: 1,
    subject: "civics",
    difficulty: "easy",
    grade: "Grade 12",
    topic: "Democracy",
    explanation:
      "Elections allow citizens to choose leaders, express preferences, and ensure government accountability",
    year: 2022,
  },
];

module.exports = questions;
